### ISSUE TITLE
international money amount and currency

### ISSUE THREAD

**Issue by pvdbosch** [belgif/openapi-money#2]
Support international money amounts by defining:
* a Currency type
* a type for the numerical money amount

To determine final naming of the types, an issue in fedvoc repo will be created.

For Currency, base on https://en.wikipedia.org/wiki/ISO_4217#Active_codes
```
Currency:
  type: string
  pattern: ^[A-Z]{3}$
  example: EUR
```

For amount:
* representation of decimals => see https://github.com/belgif/rest-guide/issues/79
* money amount can, according to the ISO codes, have 0 up to 4 decimal digits. Expressing the amount as integers is tricky then because you need to know where to place the comma
* EuroCentAmount can still be kept for use cases (APIs) where the currency is always Euro
* It is common that negative amounts are not allowed for a use case. We could, similarly to EuroCentPositiveAmount, create an additional type that only allows for positive amounts. 

We could create an additional Money type to combine Currency and MoneyAmount in a composite type (also PositiveMoney then?)

For comparison: [Zalando Money type](https://opensource.zalando.com/restful-api-guidelines/#173).

**Comment by pvdbosch** [comment]
current draft for international money types, based on updated FedVoc draft in https://github.com/belgif/fedvoc/issues/17

```yaml
    Currency: # do we add Code suffix?
      description: A currency represented by its ISO 4217 alpha code
      type: string
      pattern: "^[A-Z]{3}$"
      example: "EUR"
    MonetaryAmount:
      description: A monetary value
      type: object
      properties:
        value:
          "$ref": "#/components/schemas/Decimal"
        currency:
          "$ref": "#/components/schemas/Currency"
      required: [value, currency]
      example:
        value: "0.01"
        currency: "EUR"
```

discussion on Decimal type is continued in https://github.com/belgif/rest-guide/issues/79
